auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “PkerPker's Blog”
title: PkerPker's blog
description: Everything about PkerPkere.
url: http://shmily614.github.io
feed: /atom.xml
author_info: <a href="http://shmily614.github.io/">PkerPker</a>
